name: CD Pipeline

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE: flight-delay-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        pip install -r requirements-dev.txt
        pip install locust
    
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
    
    - name: Build and push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/$SERVICE/$SERVICE:${{ github.sha }} .
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/$SERVICE/$SERVICE:${{ github.sha }}
        
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/$SERVICE/$SERVICE:${{ github.sha }} \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated
          
    - name: Wait for deployment and run stress tests
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 30
        
        mkdir -p reports
        
        locust -f tests/stress/api_stress.py \
          --print-stats \
          --html reports/stress-test.html \
          --run-time 60s \
          --headless \
          --users 100 \
          --spawn-rate 1 \
          -H https://flight-delay-api-597687220466.us-central1.run.app
          
    - name: Upload stress test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: stress-test-results
        path: reports/stress-test.html