name: CD Pipeline

on:
  push:
    branches: [ main ]
    
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE: flight-delay-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/$PROJECT_ID/$SERVICE:${{ github.sha }} .
        docker push gcr.io/$PROJECT_ID/$SERVICE:${{ github.sha }}
        
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE \
          --image gcr.io/$PROJECT_ID/$SERVICE:${{ github.sha }} \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated
          
    - name: Run stress tests
      run: |
        sleep 30  # Wait for deployment to stabilize
        make stress-test